kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

steps:
  - name: release
    image: plugins/gitea-release
    when:
      ref:
        - refs/tags/*
    environment:
      GITEA_API_KEY:
        from_secret: gitea_api_key
      GITEA_BASE_URL:
        from_secret: gitea_base_url
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url:
        from_secret: gitea_base_url
      files: dist/*

  - name: docker
    image: plugins/docker
    privileged: true
    environment:
      USERNAME:
        from_secret: gitea_username
      PASSWORD:
        from_secret: gitea_password
      GITEA_BASE_URL:
        from_secret: gitea_base_url
    settings:
      tags: latest
      auto_tag: true
      repo: git.littlevibe.net/kuhree/resume
      registry: git.littlevibe.net
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_password
